//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessoSeletivoINTRA.Models
{
    using System;
    using System.Collections.Generic;

    public partial class venda
    {
        
        public int id_venda { get; set; }
        public int produto { get; set; }
        public float valor { get; set; }
        public System.DateTime data_venda { get; set; }
        public int quantidade { get; set; }
    
        public virtual produto produto1 { get; set; }
    }
}
